const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Follow,
		C3.Behaviors.scrollto,
		C3.Behaviors.destroy,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Behaviors.Sin,
		C3.Plugins.progressbar,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.progressbar.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet
	];
};
self.C3_JsPropNameTable = [
	{PlagueHealth: 0},
	{Platform: 0},
	{Follow: 0},
	{ScrollTo: 0},
	{DestroyOutsideLayout: 0},
	{Plague: 0},
	{Solid: 0},
	{HellStone: 0},
	{Keyboard: 0},
	{Bullet: 0},
	{Syringe: 0},
	{Mouse: 0},
	{HealthFarmer: 0},
	{Sine: 0},
	{Farmer: 0},
	{Pin: 0},
	{PlaguesHealth: 0},
	{Fork: 0},
	{MiniBossArena: 0},
	{GameOverText: 0},
	{TiledBackground: 0},
	{X: 0},
	{Text: 0},
	{InkTortHealth: 0},
	{IsAttacking: 0},
	{InkTortoise: 0},
	{TortHealth: 0},
	{InkBlob: 0},
	{InkSpike: 0},
	{Sprite2: 0},
	{InkSpike2: 0},
	{Text2: 0},
	{Sprite: 0},
	{InkMachineHp: 0},
	{InkMachine: 0},
	{InkBullet: 0},
	{EndPoint: 0}
];

self.InstanceType = {
	Plague: class extends self.ISpriteInstance {},
	HellStone: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Syringe: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Farmer: class extends self.ISpriteInstance {},
	PlaguesHealth: class extends self.IProgressBarInstance {},
	Fork: class extends self.ISpriteInstance {},
	MiniBossArena: class extends self.ISpriteInstance {},
	GameOverText: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	X: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	InkTortoise: class extends self.ISpriteInstance {},
	TortHealth: class extends self.IProgressBarInstance {},
	InkBlob: class extends self.ISpriteInstance {},
	InkSpike: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	InkSpike2: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	InkMachine: class extends self.ISpriteInstance {},
	InkBullet: class extends self.ISpriteInstance {},
	EndPoint: class extends self.ISpriteInstance {}
}