const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Arr,
		C3.Plugins.progressbar,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Arr.Acts.SetInstanceVar,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Text.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.LoadState
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Bridge: 0},
	{previousTurnTakeUID: 0},
	{turn: 0},
	{ZuessHealth: 0},
	{Zues: 0},
	{Health: 0},
	{Harpy: 0},
	{Mouse: 0},
	{anubishealth: 0},
	{Anubis: 0},
	{TurnBox: 0},
	{Turn: 0},
	{TurnOrder: 0},
	{TrueFalse: 0},
	{LightningBolt: 0},
	{TFV2: 0},
	{HeavensAnger: 0},
	{TrueFalse2: 0},
	{StaffAttack: 0},
	{TFV: 0},
	{Mummified: 0},
	{Pin: 0},
	{HARPYHEALTHBAR: 0},
	{ZUESHEALTHBAR: 0},
	{ANUBISHEALTHBAR: 0},
	{ProgressBar: 0},
	{Audio: 0},
	{YOUWINSTINKYBUTT: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{hadestext: 0},
	{Text: 0},
	{Sprite3: 0},
	{TurnTakers: 0},
	{WhoseTurnIsIt: 0},
	{Istheturnending: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Bridge: class extends self.ISpriteInstance {},
	Zues: class extends self.ISpriteInstance {},
	Harpy: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Anubis: class extends self.ISpriteInstance {},
	TurnBox: class extends self.ISpriteInstance {},
	TurnOrder: class extends self.IArrayInstance {},
	LightningBolt: class extends self.ISpriteInstance {},
	HeavensAnger: class extends self.ISpriteInstance {},
	StaffAttack: class extends self.ISpriteInstance {},
	Mummified: class extends self.ISpriteInstance {},
	HARPYHEALTHBAR: class extends self.IProgressBarInstance {},
	ZUESHEALTHBAR: class extends self.IProgressBarInstance {},
	ANUBISHEALTHBAR: class extends self.IProgressBarInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	Audio: class extends self.IInstance {},
	YOUWINSTINKYBUTT: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	hadestext: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TurnTakers: class extends self.ISpriteInstance {}
}